TelerikMvcAppTestSwitch_Backup_2023.07.17_01.28.50/Models/PodcastViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TelerikMvcAppTestSwitch.Models
{
    public class PodcastViewModel
    {
        private int views;

        public string Name { get; set; }

        public int Downloads { get; set; }

        public int Streams { get; set; }

        public int Views
        {
            get
            {
                return Downloads + Streams;
            }
            private set
            {
                views = value;
            }
        }

        public DateTime Date { get; set; }

        public int Reach { get; set; }

        public string Device { get; set; }

        public string PlatformName { get; set; }
    }

    public class SwitchTestViewModel
    {
        public Boolean someBool { get; set; }
        public String someString { get; set; }
    }
}

TelerikMvcAppTestSwitch_Backup_2023.07.17_01.28.50/Controllers/DashboardController.cs
using System;
﻿using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using TelerikMvcAppTestSwitch.Models;

namespace TelerikMvcAppTestSwitch.Controllers
{
	public partial class DashboardController : Controller
    {
        public static Random random = new Random();
        public static List<string> firstNames = new List<string> { "Nancy", "Andrew", "Janet", "Margaret", "Steven", "Michael", "Robert", "Laura", "Anne", "Nige" };
        public static List<string> lastNames = new List<string> { "Davolio", "Fuller", "Leverling", "Peacock", "Buchanan", "Suyama", "King", "Callahan", "Dodsworth", "White" };
        public static List<string> platforms = new List<string> { "Apple Podcasts", "Spotify", "Other", "Overcast", "Anchor", "Stitcher" };
        public static List<string> devices = new List<string> { "iOS", "Android", "Other", "Web" };
        public static List<PodcastViewModel> podcasts = new List<PodcastViewModel>();

        public ActionResult Podcasts_Read([DataSourceRequest] DataSourceRequest request)
        {

            var result = GetPodcasts().ToDataSourceResult(request);
            return Json(result);
        }

        public ActionResult Downloads_Read([DataSourceRequest] DataSourceRequest request)
        {
            return Json(GetPodcasts(), JsonRequestBehavior.AllowGet);
        }

        public ActionResult Devices_Read([DataSourceRequest] DataSourceRequest request)
        {
            var deviceViews = GetPodcasts().GroupBy(x => x.Device)
                                .Select(x => new
                                {
                                    Device = x.Key,
                                    Views = x.Sum(v => v.Views)
                                });
            return Json(deviceViews);
        }

        public ActionResult Platforms_Read([DataSourceRequest] DataSourceRequest request)
        {
            var platformViews = GetPodcasts().GroupBy(x => x.PlatformName)
                                .Select(x => new
                                {
                                    PlatformName = x.Key,
                                    Views = x.Sum(v => v.Views)
                                });

            return Json(platformViews);
        }
        private IEnumerable<PodcastViewModel> GetPodcasts()
        {
            if (podcasts.Count == 0)
            {
                podcasts = Enumerable.Range(1, 50).Select(x => new PodcastViewModel()
                {
                    Name = string.Format("Episode #{0} with guest {1} {2}", random.Next(0, 200), firstNames[random.Next(0, firstNames.Count)], lastNames[random.Next(0, lastNames.Count)]),
                    Streams = random.Next(0, 18000),
                    Downloads = random.Next(0, 15000),
                    PlatformName = platforms[random.Next(0, platforms.Count)],
                    Device = devices[random.Next(0, devices.Count)],
                    Date = DateTime.Now.AddDays(-x),
                    Reach = x * random.Next(0, 1000),
                }).ToList();
            }

            return podcasts;
        }
    }
}

TelerikMvcAppTestSwitch_Backup_2023.07.17_01.28.50/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TelerikMvcAppTestSwitch.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Message = "Welcome to ASP.NET MVC!";

            return View();
        }
    }
}

TelerikMvcAppTestSwitch_Backup_2023.07.17_01.28.50/Controllers/SwitchTestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TelerikMvcAppTestSwitch.Models;

namespace TelerikMvcAppTestSwitch.Controllers
{
    public class SwitchTestController : Controller
    {
        // GET: SwitchTest
        public ActionResult Index()
        {
            var model = new SwitchTestViewModel();
            model.someString = "sample Name";
            model.someBool = true;

            return View(model);
        }

        public ActionResult AddNew()
        {
            var model = new SwitchTestViewModel();
            model.someString = "new Name";
            model.someBool = false;

            return View(model);
        }
    }
}

TelerikMvcAppTestSwitch_Backup_2023.07.17_01.28.50/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<style>
    .k-footer-template {
        display: none;
    }

    .k-card-header {
        flex: 0 0 auto;
    }

    .k-card-body {
        overflow: hidden;
    }
</style>

<!-- container text templates -->
<script id="total-streams-template" type="text/x-kendo-template">
    <h2 id="total-streams"></h2>
</script>
<script id="total-downloads-template" type="text/x-kendo-template">
    <h2 id="total-downloads"></h2>
</script>
<script id="reach-template" type="text/x-kendo-template">
    <h2 id="total-reach"></h2>
</script>
<script id="revenue-template" type="text/x-kendo-template">
    <h2 id="total-revenue"></h2>
</script>

<!-- container chart templates -->
<script id="downloads-chart-template" type="text/x-kendo-template">
    @(Html.Kendo().Chart()
        .Name("downloads")
        // to configure the chart theme to match the application theme use the theme setting
        // https://docs.telerik.com/kendo-ui/api/javascript/dataviz/ui/chart/configuration/theme
        //.Theme("sass")  _
        .Series(s=>s.Line("Downloads", categoryMemberName: "Date"))
        .Legend(l=>l.Visible(false))
        .CategoryAxis(c=>
            c.Date()
            .BaseUnit(ChartAxisBaseUnit.Fit)
            .Labels(l => l.Format("{0:d MMM}").Rotation("auto"))
            .MajorGridLines(mg => mg.Visible(false))
            .MajorTicks(mt => mt.Visible(false))
        )
        .ValueAxis(v=>v.Numeric().Min(1000).Max(16000).Labels(l => l.Step(4)))
        .DataSource("dateChartDataSource")
        .HtmlAttributes(new { style = "height:100%;width:100%;" })
        .ToClientTemplate()
    )
</script>
<script id="performance-chart-template" type="text/x-kendo-template">
    @(Html.Kendo().Chart()
        .Name("performance")
        // to configure the chart theme to match the application theme use the theme setting
        // https://docs.telerik.com/kendo-ui/api/javascript/dataviz/ui/chart/configuration/theme
        //.Theme("sass")  _
        .AutoBind(false)
        .Series(s=>s.Column("Views", categoryMemberName: "Date"))
        .Legend(l=>l.Visible(false))
        .CategoryAxis(c=>
            c.Date()
            .BaseUnit(ChartAxisBaseUnit.Fit)
            .Labels(l => l.Format("{0:d MMM}").Rotation("auto"))
            .MajorGridLines(mg => mg.Visible(false))
            .MajorTicks(mt => mt.Visible(false))
        )
        .ValueAxis(v => v.Numeric().Min(4000).Max(30000).Labels(l=>l.Step(3)))
        .DataSource("dateChartDataSource")
        .HtmlAttributes(new { style = "height:100%;width:100%;" })
        .ToClientTemplate()
    )
</script>
<script>
    function donutCategoryLabels(e) {
        return new kendo.drawing.Text(e.category, e.rect.origin);
    }
</script>

<script id="apps-chart-template" type="text/x-kendo-template">
    @(Html.Kendo().Chart()
        .Name("devices")
        // to configure the chart theme to match the application theme use the theme setting
        // https://docs.telerik.com/kendo-ui/api/javascript/dataviz/ui/chart/configuration/theme
        //.Theme("sass")  _
        .Series(s=>s.Donut("Views", "Device")
            .AutoFit()
            .Labels(labels => labels
            .Visible(true)
            .Visual("donutCategoryLabels")
            .Position(ChartPieLabelsPosition.OutsideEnd)
            )
        )
        .Legend(l=>l.Visible(false))
        .DataSource(d=>d.Read("Devices_Read", "Dashboard"))
        .HtmlAttributes(new { style = "height:100%;width:100%;" })
        .ToClientTemplate()
    )
</script>

<script id="platforms-chart-template" type="text/x-kendo-template">
    @(Html.Kendo().Chart<TelerikMvcAppTestSwitch.Models.PodcastViewModel>()
        .Name("platforms")
        // to configure the chart theme to match the application theme use the theme setting
        // https://docs.telerik.com/kendo-ui/api/javascript/dataviz/ui/chart/configuration/theme
        //.Theme("sass")  _
        .Series(s=>
            s.Donut(model => model.Views, model => model.PlatformName)
            .AutoFit()
            .Labels(labels => labels
            .Visible(true)
            .Visual("donutCategoryLabels")
            .Position(ChartPieLabelsPosition.OutsideEnd)
          )
        )
        .DataSource(d => d.Read("Platforms_Read", "Dashboard"))
        .Legend(l=>l.Visible(false))
        .HtmlAttributes(new { style = "height:100%;width:100%;" })
        .ToClientTemplate()
    )
</script>

<!-- container grid template -->
<script id="grid-template" type="text/x-kendo-template">
    @(Html.Kendo().Grid<TelerikMvcAppTestSwitch.Models.PodcastViewModel>()
        .Name("Grid")
        .Columns(columns =>
        {
            columns.Bound(p => p.Name).Title("Podcast Episode").Width(320);
            columns.Bound(p => p.Streams).Width(150);
            columns.Bound(p => p.Downloads).Width(250);
        })
        .Sortable()
        .Scrollable(s=>s.Height("auto"))
        .HtmlAttributes(new { style = "height:100%;" })
        .DataSource(dataSource => dataSource
            .Ajax()
            .PageSize(5)
            .Sort(s=>s.Add(f=>f.Streams).Descending())
            .Read("Podcasts_Read", "Dashboard")
            .Aggregates(a =>
            {
                a.Add(f => f.Downloads).Sum();
                a.Add(f => f.Streams).Sum();
                a.Add(f => f.Reach).Sum();
                a.Add(f => f.Views).Sum();
            })
        )
        .Events(e=>e.DataBound("populateTotals"))
        .ToClientTemplate()
     )
</script>

<div class="d-flex justify-content-center">
    @(Html.Kendo().DataSource<TelerikMvcAppTestSwitch.Models.PodcastViewModel>()
        .Name("dateChartDataSource")
        .Custom(d=>
         d.Transport(t => t.Read("Downloads_Read", "Dashboard"))
        )
    )

    @(Html.Kendo().TileLayout()
            .Name("tilelayout")
            .Columns(4)
            .RowsHeight("145px")
            .ColumnsWidth("350px")
            .Containers(c => {
                c.Add().Header(h => h.Text("Total Streams")).BodyTemplateId("total-streams-template").ColSpan(1).RowSpan(1);
                c.Add().Header(h => h.Text("Total Downloads")).BodyTemplateId("total-downloads-template").ColSpan(1).RowSpan(1);
                c.Add().Header(h => h.Text("Reach")).BodyTemplateId("reach-template").ColSpan(1).RowSpan(1);
                c.Add().Header(h => h.Text("Revenue")).BodyTemplateId("revenue-template").ColSpan(1).RowSpan(1);
                c.Add().Header(h => h.Text("Weekly Recap-Downloads")).BodyTemplateId("downloads-chart-template").ColSpan(2).RowSpan(3);
                c.Add().Header(h => h.Text("Performance Trend")).BodyTemplateId("performance-chart-template").ColSpan(2).RowSpan(3);
                c.Add().Header(h => h.Text("Top 5 Episodes")).BodyTemplateId("grid-template").ColSpan(4).RowSpan(2);
                c.Add().Header(h => h.Text("Listening platforms-Apps")).BodyTemplateId("apps-chart-template").ColSpan(2).RowSpan(2);
                c.Add().Header(h => h.Text("Listening platforms-Devices")).BodyTemplateId("platforms-chart-template").ColSpan(2).RowSpan(2);
            })
            .Reorderable(true)
            .Resizable(true)
            .Events(e=>e.Resize("onTileResize"))
        )
    <script>
        function onTileResize(e) {
            var container = e.item || e.container;
            if (container) {

                // for widgets that do not auto resize
                // https://docs.telerik.com/kendo-ui/styles-and-layout/using-kendo-in-responsive-web-pages
                kendo.resize(container, true);
            }
        }

        function populateTotals(e) {
            // we are using the aggregates of the grid to populate our totals
            var aggregates = e.sender.dataSource.aggregates();

            $("#total-streams").html(kendo.toString(aggregates.Streams.sum, "n0"));
            $("#total-downloads").html(kendo.toString(aggregates.Downloads.sum, "n0"));
            $("#total-reach").html(kendo.toString(aggregates.Reach.sum, "n0"));
            $("#total-revenue").html(kendo.toString(aggregates.Views.sum / 100, "c0"));
        }
    </script>
</div>

TelerikMvcAppTestSwitch_Backup_2023.07.17_01.28.50/Views/Shared/EditorTemplates/Boolean.cshtml
@model bool?

@(Html.Kendo().CheckBoxFor(m => m).HtmlAttributes(new { title = Html.ViewContext.ViewData.TemplateInfo.GetFullHtmlFieldName("")}))

TelerikMvcAppTestSwitch_Backup_2023.07.17_01.28.50/Views/Shared/EditorTemplates/Country.cshtml
@model string

@(Html.Kendo().DropDownListFor(m => m)
            .DataValueField("CountryNameShort")
            .DataTextField("CountryNameLong")
            .HtmlAttributes(new { data_bind = "value: Country" })
            .Template(@"<div class='dropdown-country-wrap'><img src='" + @Url.Content("~/content/web/country-flags/#:data.CountryNameShort#.png") + "' alt='#: data.CountryNameLong#' title='#: data.CountryNameLong#' width='20' /><span>#: data.CountryNameLong #</span></div>")
            .BindTo((System.Collections.IEnumerable)ViewData["countries"])
            .AutoWidth(true)
)

TelerikMvcAppTestSwitch_Backup_2023.07.17_01.28.50/Views/Shared/EditorTemplates/Currency.cshtml
@model decimal?

@(Html.Kendo().CurrencyTextBoxFor(m => m)
      .HtmlAttributes(new { style = "width:100%", title = Html.ViewContext.ViewData.TemplateInfo.GetFullHtmlFieldName("")})
      .Min(0)
)

TelerikMvcAppTestSwitch_Backup_2023.07.17_01.28.50/Views/Shared/EditorTemplates/Date.cshtml
@model DateTime?

@(Html.Kendo().DatePickerFor(m => m).HtmlAttributes(new { title = Html.ViewContext.ViewData.TemplateInfo.GetFullHtmlFieldName("")}))

TelerikMvcAppTestSwitch_Backup_2023.07.17_01.28.50/Views/Shared/EditorTemplates/DateTime.cshtml
@model DateTime?

@(Html.Kendo().DateTimePickerFor(m => m).HtmlAttributes(new { title = Html.ViewContext.ViewData.TemplateInfo.GetFullHtmlFieldName("")}))

TelerikMvcAppTestSwitch_Backup_2023.07.17_01.28.50/Views/Shared/EditorTemplates/Email.cshtml
@model object 

<span class="k-input k-textbox k-input-solid k-input-md k-rounded-md">
    @Html.TextBoxFor(model => model, new { @class = "k-input-inner"})
</span>

TelerikMvcAppTestSwitch_Backup_2023.07.17_01.28.50/Views/Shared/EditorTemplates/EmailAddress.cshtml
@model object 

<span class="k-input k-textbox k-input-solid k-input-md k-rounded-md">
    @Html.TextBoxFor(model => model, new { @class = "k-input-inner", type = "email" })
</span>

TelerikMvcAppTestSwitch_Backup_2023.07.17_01.28.50/Views/Shared/EditorTemplates/GridForeignKey.cshtml
@model object

@(
 Html.Kendo().DropDownListFor(m => m)
        .BindTo((SelectList)ViewData[ViewData.TemplateInfo.GetFullHtmlFieldName("") + "_Data"])
        .HtmlAttributes(new { title = Html.ViewContext.ViewData.TemplateInfo.GetFullHtmlFieldName("")})
)

TelerikMvcAppTestSwitch_Backup_2023.07.17_01.28.50/Views/Shared/EditorTemplates/Integer.cshtml
@model int?

@(Html.Kendo().IntegerTextBoxFor(m => m)
      .HtmlAttributes(new { style = "width:100%", title = Html.ViewContext.ViewData.TemplateInfo.GetFullHtmlFieldName("")})
      .Min(int.MinValue)
      .Max(int.MaxValue)
)

TelerikMvcAppTestSwitch_Backup_2023.07.17_01.28.50/Views/Shared/EditorTemplates/Number.cshtml
@model double?

@(Html.Kendo().NumericTextBoxFor(m => m)
      .HtmlAttributes(new { style = "width:100%" })
      .HtmlAttributes(new { title = Html.ViewContext.ViewData.TemplateInfo.GetFullHtmlFieldName("")})
)

TelerikMvcAppTestSwitch_Backup_2023.07.17_01.28.50/Views/Shared/EditorTemplates/Password.cshtml
@model object 

<span class="k-input k-textbox k-input-solid k-input-md k-rounded-md">
    @Html.TextBoxFor(model => model, new { @class = "k-input-inner", type = "password" })
</span>

TelerikMvcAppTestSwitch_Backup_2023.07.17_01.28.50/Views/Shared/EditorTemplates/String.cshtml
@model object 

@Html.Kendo().TextBoxFor(model => model)

TelerikMvcAppTestSwitch_Backup_2023.07.17_01.28.50/Views/Shared/EditorTemplates/Time.cshtml
@model DateTime?

@(Html.Kendo().TimePickerFor(m => m).HtmlAttributes(new {title = Html.ViewContext.ViewData.TemplateInfo.GetFullHtmlFieldName("")}))

TelerikMvcAppTestSwitch_Backup_2023.07.17_01.28.50/Views/Shared/EditorTemplates/Url.cshtml
@model object 

<span class="k-input k-textbox k-input-solid k-input-md k-rounded-md">
    @Html.TextBoxFor(model => model, new { @class = "k-input-inner", type = "url" })
</span>

TelerikMvcAppTestSwitch_Backup_2023.07.17_01.28.50/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title - My Telerik MVC Application</title>
	<link href="https://kendo.cdn.telerik.com/themes/6.2.0/default/default-ocean-blue.css" rel="stylesheet" type="text/css" />
	<link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" type="text/css" />
	<link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
	<script src="https://cdn.kendostatic.com/2023.1.425/js/jquery.min.js"></script>
	<script src="https://cdn.kendostatic.com/2023.1.425/js/jszip.min.js"></script>
	<script src="https://cdn.kendostatic.com/2023.1.425/js/kendo.all.min.js"></script>
	<script src="https://cdn.kendostatic.com/2023.1.425/js/kendo.aspnetmvc.min.js"></script>
	<script src="@Url.Content("~/Scripts/bootstrap.min.js")"></script>
</head>
<body class="k-content">
    <nav class="navbar navbar-dark bg-dark">
        <div class="container-fluid d-flex justify-content-between p-0">
            <h1 class="navbar-brand d-flex align-items-center">Dashboard Template</h1>
        </div>
    </nav>

    <main>
        <div>
            testy
            @RenderBody()
        </div>
    </main>
    <div id="ActionWindow"></div>

    <footer class="footer text-center d-flex align-items-center">
        <div class="container-fluid">
            <p class="text-muted">Copyright © @DateTime.Now.Year Progress Software Corporation and/or its subsidiaries or affiliates. All Rights Reserved.</p>
        </div>
    </footer>
</body>
</html>

TelerikMvcAppTestSwitch_Backup_2023.07.17_01.28.50/Views/SwitchTest/AddNew.cshtml
@model TelerikMvcAppTestSwitch.Models.SwitchTestViewModel
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AddNew</title>
</head>
<body>
    <div class="row">
        <div class="col-md-2">
            @(Html.Kendo().SwitchFor(model=>model.someBool))
        </div>
        <div class="col-md-6">
            @(Html.Kendo().TextBoxFor(model=>model.someString))
        </div>
        <div class="col-md-4">
            <button id="bExit" onclick='@Url.Action("Index", "SwitchTest")'> exit </button>
        </div>

    </div>
</body>
</html>

TelerikMvcAppTestSwitch_Backup_2023.07.17_01.28.50/Views/SwitchTest/Index.cshtml
@model TelerikMvcAppTestSwitch.Models.SwitchTestViewModel
@{
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <script src="@Url.Content("~/Scripts/app.js")"></script>

</head>
<body>
        <div class="row row-2">
            <div class="col-md-2">
                @(Html.Kendo().Switch().Name("randomName"))
            </div>
            <div class="col-md-6">
                @(Html.Kendo().TextBoxFor(model => model.someString))
            </div>
            <div class="col-md-4">
                <button id="button" onclick="runAction(400,200)"> add New </button>
            </div>
        </div>
    </body>
</html>